set_property PACKAGE_PIN W5 [get_ports EXCLK]
set_property PACKAGE_PIN R2 [get_ports button]
set_property PACKAGE_PIN A18 [get_ports Tx]
set_property PACKAGE_PIN B18 [get_ports Rx]
set_property IOSTANDARD LVCMOS33 [get_ports EXCLK]
set_property IOSTANDARD LVCMOS33 [get_ports button]
set_property IOSTANDARD LVCMOS33 [get_ports Tx]
set_property IOSTANDARD LVCMOS33 [get_ports Rx]